{"ua":"{\"clickCloseUa\":\"|XIANGQIN_APP|VivoBrowser|QQLiveBrowser|JDLightApp|baidumap|SamsungBrowser|junion-app|yyb_version|JDAPPERSHOU|\",\"closeUaMoreKeys\":[{\"uaMoreKeys\":\"baiduboxapp|light\"}],\"universalLinksUa\":\"baidubrowser|baiduboxapp|\",\"universalLinksOs\":\"9|10|\",\"universalLinksUaAuto\":\"o\",\"universalLinksOsAuto\":\"9|10|\",\"autoCloseOs\":[{\"os\":\"\",\"abtest\":\"\"}],\"autoCloseBrowser\":[{\"browser\":\"\",\"abtest\":\"\"}],\"autoCloseOsAndBrowser\":[{\"os\":\"\",\"browser\":\"\",\"abtest\":\"\"}],\"appDownCloseIntervalTime\":86400000,\"appDownOpenIntervalTime\":0}"}